<?php
/**
 * Copyright © MagePal LLC. All rights reserved.
 * See COPYING.txt for license details.
 * http://www.magepal.com | support@magepal.com
 */

/** @var $block MagePal\EditOrderEmail\Block\Adminhtml\Email\Edit */

$checked = $block->getAutocheckEmail() == 1 ? 'checked' : '';
?>

<div id="mp_edit_order_email">
    <p>Please enter the new email address</p>
    <input type="email" data-validate='{"required":true, "validate-email":true}' name="email" />
    <input type="hidden" name="order_id" value="<?php echo $block->getOrderId() ?>" />
    <input type="hidden" name="old_email" value="<?php echo $block->getEmailAddress() ?>" />
    <input type="checkbox" name="update_customer_email" value="<?= $block->getAutocheckEmail() ?>" <?= $checked ?>> Update Customer Record<br>
    <span class="errormsg"></span>
    <button id="mpSaveNewEmailFormPost">Save</button>
</div>


<script type="text/x-magento-init">
    {
        "*": {
            "magePalEditOrderEmail": {"postUrl":"<?php echo $block->getAdminPostUrl() ?>"}
        }
    }
</script>